refactor(scripting/lua): Citizen.Await promise handling
citizenfx/fivem pull request #1202
Opened 2021-12-26 11:42 UTC by thelindat

I was having a look at Citizen.Await / promises and noticed some weird hack, despite promises exposing state and value (maybe based on some old code?). I didn't experience any unexpected behaviour with this change to the implementation.

Change to main.js returns the actual error message, rather than an empty object in the Lua runtime.
![image](https://user-images.githubusercontent.com/65407488/147406024-e0e86534-a66d-463d-82b8-06f606756ccb.png)
![image](https://user-images.githubusercontent.com/65407488/147406099-fda49f24-1678-47f3-8fcf-7fabfe2d4f7f.png)

2021-12-27 10:37 UTC, blattersturm requested changes
not gonna merge a typo :D

Odd how the person who PR'd this long ago (#75) did this when apparently the library they imported _did_ make state accessible.

2021-12-27 10:37 UTC, blattersturm commented on data/shared/citizen/scripting/lua/scheduler.lua
> +		error(('An error occured while calling export %s of resource %s\n%s'):format(exportName, resource, result))
How'd you end up introducing a typo?

2021-12-27 10:50 UTC, thelindat commented on data/shared/citizen/scripting/lua/scheduler.lua
> +		error(('An error occured while calling export %s of resource %s\n%s'):format(exportName, resource, result))
😊 general incompetence

2021-12-28 16:35 UTC, blattersturm commented
i don't think our commit categorization likes `refactor` much. we need a `internal` category or so someday but for now `tweak`

2021-12-28 16:45 UTC, thelindat commented
> i don't think our commit categorization likes `refactor` much. we need a `internal` category or so someday but for now `tweak`

Amended to tweak. Is there somewhere I can view the acceptable categories?

2021-12-30 05:50 UTC, blattersturm commented
> Is there somewhere I can view the acceptable categories?

No, I don't think so. This may be in the changelog code but I'm not sure if this is on the client or server side.

2021-12-30 05:50 UTC, blattersturm approved these changes

2022-01-01 18:08 UTC, merged