feat(extra-natives/rdr3): setter to ignore hunting wagon's stowing checks related to ownership.
citizenfx/fivem pull request #1660
Opened 2022-10-14 17:56 UTC by slashkeyvalue

Normally you'd have to set _SET_PLAYER_OWNS_VEHICLE(0xD0E02AA618020D17) and _SET_PLAYER_HUNTING_WAGON(0x6A4404BDFA62CE2C) to be able to stow carriables in a specific hunting wagon, so what this native does is it disables a couple of the checks related to that.

2022-10-14 17:59 UTC, LWSS commented
`code/build/rdr3/VehicleNatives.cpp`

shouldn't put stuff in the build/ folder, try somewhere in code/components/

2022-10-14 18:19 UTC, slashkeyvalue commented
done.

2022-10-14 18:22 UTC, blattersturm commented
> `code/build/rdr3/VehicleNatives.cpp`
> 
> shouldn't put stuff in the build/ folder, try somewhere in code/components/

thanks, visual studio :(

2022-10-14 22:02 UTC, Disquse commented
Gonna do a proper review a bit later, but I see that you never reset `g_ignoreVehicleOwnershipChecksForStowing` flag (when disconnecting from server). This might lead to confusion and unexpected behavior if a server doesn't use this native.

2022-10-14 23:13 UTC, slashkeyvalue commented
> Gonna do a proper review a bit later, but I see that you never reset `g_ignoreVehicleOwnershipChecksForStowing` flag (when disconnecting from server). This might lead to confusion and unexpected behavior if a server doesn't use this native.

also done.

2022-12-04 02:44 UTC, Disquse requested changes

2022-12-04 02:44 UTC, Disquse commented on code/components/extra-natives-rdr3/src/VehicleNatives.cpp
> +			sub(rsp, 0x16);
`0x16` sounds super weird, use `0x18` at least.

2022-12-04 02:44 UTC, Disquse commented on code/components/extra-natives-rdr3/src/VehicleNatives.cpp
> +			add(rsp, 0x16);
Same here.

2022-12-04 18:33 UTC, Disquse approved these changes

2023-01-04 16:16 UTC, slashkeyvalue commented
welp

2023-01-04 16:33 UTC, blattersturm commented
squash maybe?

also we're super backlogged on everything- not just PRs

2023-01-04 16:41 UTC, slashkeyvalue commented
no worries, just thought i was missing something else.
will do the squashing.

2023-01-04 18:04 UTC, merged