tweak(onesync): Change f164 to weaponHash for explosionEvent
citizenfx/fivem pull request #1768
Opened 2022-12-31 15:31 UTC by niekschoemaker

2022-12-31 15:47 UTC, AvarianKnight commented
You should keep the old parameter for backwards compatibility but add new ones with the proper names, you can see [an old pr](https://github.com/citizenfx/fivem/pull/785/files) for reference

2023-01-03 12:53 UTC, blattersturm requested changes

2023-01-03 12:53 UTC, blattersturm commented on code/components/citizen-server-impl/src/state/ServerGameState.cpp
> +	uint32_t weaponHash;
See @AvarianKnight's comment above.

2024-09-06 12:38 UTC, prikolium-cfx commented
Closed as stale.

2024-09-06 12:38 UTC, closed without merging