Update SetWeaponsNoAutoSwap.md
citizenfx/fivem pull request #1792
Opened 2023-01-10 02:16 UTC by orel56000

Added informtaion about a r* behavior bug

2023-03-20 19:10 UTC, blattersturm requested changes
Style issue, also the commit message is ~wrongly formatted.

2023-03-20 19:10 UTC, blattersturm commented on ext/native-decls/SetWeaponsNoAutoSwap.md
> +This native won't have any affect if setting flag 48 to true, using SetPedConfigFlag native.
Adding descriptions below 'Parameters' won't show at all. Also, why is this in code blocks?

2023-05-15 16:28 UTC, ahcenezdh commented
"This native will not have any effect if the flag 48 is set to true when using the SetPedConfigFlag native."

2024-03-04 14:25 UTC, 4mmonium requested changes
Hi, @orel56000 check the comments by blattersturm. Things such as descriptions cannot be under the `# Parameters` section, they should be above it, native description shouldn't be in code blocks as well, that's reserved for native db import descriptions.

I will un-assign myself since I don't have much else to add here.

2024-03-22 00:42 UTC, gottfriedleibniz commented
Closing as stale. Please reopen if you would continue this work.

2024-03-22 00:42 UTC, closed without merging