feat(citizen-scripting-v8): add ability to change max-old-space-size
citizenfx/fivem pull request #1796
Opened 2023-01-13 06:07 UTC by Nova-px

Adds the ability to change the flag value for max-old-space-size via a variable to prevent heap out of memory crashes

2023-01-13 06:44 UTC, AvarianKnight commented
Isn't this already possible by just passing the argument to FXServer, or if you're on txAdmin passing it in the additional arguments

2023-01-13 20:34 UTC, AvarianKnight commented
Seems I was wrong, using `--inspect` and `--trace-gc` work fine but using `--max-old-space-size=8000` does not

2023-03-20 19:09 UTC, blattersturm requested changes

2023-03-20 19:13 UTC, Nova-px commented on code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp
> +	auto maxOldSpaceSize = console::GetDefaultContext()->GetVariableManager()->FindEntryRaw("node_maxOldSpaceSize");
No, I thought developers who need it could add it manually in the server.cfg

2024-01-23 23:49 UTC, MonkeyWhisper commented
We need this, thanks! 🙌

2024-06-14 13:03 UTC, ahcenezdh commented
Can be closed since #2377 was merged, @prikolium-cfx

2024-06-20 08:14 UTC, closed without merging