tweak(scripting/csharp): Add ai blip functions
citizenfx/fivem pull request #2062
Opened 2023-06-19 19:43 UTC by PappaNiels

This is an alternative pull request to #1949 . After some discussing with thorium and de C# scripters, we decided this would be the best option out of the two pull requests. This pull request puts the ai blip features in the ped class instead of making a separate class. You can decide which one to use.

2023-06-20 09:53 UTC, thorium-cfx requested changes

2023-06-20 09:53 UTC, thorium-cfx commented on code/client/clrcore/External/Ped.cs
> +namespace CitizenFX.Core
Only new line changes? better discard it

2023-06-20 21:02 UTC, PappaNiels commented
forgot to add a 'check' method and a method to disable the ai blip. its there now :)

2023-06-21 08:51 UTC, thorium-cfx approved these changes

2023-06-26 15:39 UTC, merged