feat(net): attribute proper packet names for timeout
citizenfx/fivem pull request #2141
Opened 2023-08-04 04:56 UTC by AvarianKnight

if a player times out instead of getting the packet hash they will get the packet name

![](https://i.imgur.com/IMpYlL2.png)

2023-08-04 05:12 UTC, LWSS commented
Looks good, but while ur at it, maybe add the hash as a // comment so we can ctrl-f for it sometime later

2023-10-19 10:52 UTC, blattersturm requested changes

2023-10-19 10:52 UTC, blattersturm commented on code/shared/KnownPackets.h
> +constexpr std::pair<uint32_t, const char*> g_knownPackets[]
`inline` might still be needed in case this ends up used twice in the same module.

2023-10-19 10:52 UTC, blattersturm commented on code/shared/KnownPackets.h
> +#include "Utils.h"
I think this include is already assumed to exist fine.

2023-10-19 10:52 UTC, blattersturm commented on code/shared/KnownPackets.h
> +#include <utility>
Same goes for this one.

2023-10-19 13:12 UTC, AvarianKnight commented
Applied the requested changes, also replaced g_knownPackets in NetDebug to use g_knownPackets

2023-11-03 15:21 UTC, thorium-cfx requested changes

2023-11-03 17:54 UTC, thorium-cfx commented on code/shared/KnownPackets.h
> +inline constexpr std::pair<uint32_t, const char*> g_knownPackets[]
Good call on the other code, had a proper look and seems like they're better optimized as-is for those use cases.

2023-11-03 18:06 UTC, thorium-cfx requested changes
2 more things that stand out
1. Can you move `KnownPackets.h` in a subfolder called `net` and put it in namespace `fx::net`?
2. See comment below

2023-11-03 18:06 UTC, thorium-cfx commented on code/components/debug-net/src/NetDebug.cpp
>  	}
Seeing our lists are the same now, we can just refer to the original and not make a copy

2024-06-11 06:03 UTC, AvarianKnight commented
This pretty simple PR has been sitting for 9 months, so I'm going to assume the changes are unwanted.

2024-06-11 15:27 UTC, FabianTerhorst approved these changes

2024-06-13 13:31 UTC, merged