tweak(scripting-mono-v2): bump pilot date
citizenfx/fivem pull request #2189
Opened 2023-09-06 01:02 UTC by Nova-px

Bump pilot date to 2023-11-31 because it's currently outdated

2023-09-07 10:05 UTC, thorium-cfx requested changes
Some date/day issues

2023-09-07 10:05 UTC, thorium-cfx commented on code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp
> +	constexpr int maxYear = 2023, maxMonth = 11, maxDay = 31;
November has 30 days 😏 Let's put this to December (12) instead, too much going on right now.

2023-09-07 13:56 UTC, blattersturm commented
Replacing the first commit in this PR might be better - this is now a bit tricky to merge as it'll contain both commits.

2023-09-08 18:08 UTC, AvarianKnight commented
Is it a good idea to put the pilot day during the middle of the holidays?

Also, what is the point of date locking this vs just having it under an experimental flag (kind of like rdr), as while breakages are expected, it would be a better experience for the end user to  fix their resource for any breaking changes vs the entire runtime being disabled randomly. 

Possible flag:

`use_experimental_mono_v2_runtime 'I acknowledge that the mono v2 runtime will experience API & ABI breakages, and that I will be responsible to fix my resource(s) when these breakages do happen. ' `

2023-09-08 18:20 UTC, blattersturm commented
> Also, what is the point of date locking this

To prevent the situation from RDR occurring again, where this becomes a compatibility breaking point and the temporary situation is permanent.

2023-09-09 06:20 UTC, AvarianKnight commented
> > Also, what is the point of date locking this
> 
> To prevent the situation from RDR occurring again, where this becomes a compatibility breaking point and the temporary situation turns permanent - indeed, the RDR situation isn't changeable now without breaking everything made there since 2019.
> 
> It's not only resource _authors_ being affected, it's also people buying or downloading resources written by others. Having a hard date lock means there's at least a hard deadline for resources using the preview feature to 'break', discouraging longer-term use by people who can't maintain such.

Thanks for the explanation, this makes a lot more sense when explained like that.

2023-09-23 10:36 UTC, DaniGP17 commented
Any news about this?

2023-09-23 10:45 UTC, thorium-cfx commented
> Any news about this?

We've had some technical difficulties that had to be solved first. This one is scheduled next.

Sorry for the inconvenience.

2023-09-23 10:49 UTC, thorium-cfx approved these changes

2023-09-23 13:51 UTC, DaniGP17 commented
> > Any news about this?
> 
> We've had some technical difficulties that had to be solved first. This one is scheduled next.
> 
> Sorry for the inconvenience.

Oh no problem, sorry for bothering, good luck!

2023-09-25 17:06 UTC, merged