tweak(scripting/v8): skip unnecessary payload deserialization
citizenfx/fivem pull request #2194
Opened 2023-09-08 20:51 UTC by wdesgardin

-     Skips payload deserialization when no standard event subscribers are present.
-     Fixes issue where raw event listeners weren't triggered without standard subscribers.

2023-11-03 16:12 UTC, thorium-cfx requested changes

2023-11-03 16:12 UTC, thorium-cfx commented on data/shared/citizen/scripting/v8/main.js
> +			if (listeners.length > 0) {
Prefer to see this being applied as an early out, rather than more scoping. Especially to reduce the amount of lines being changed.

2023-12-16 16:19 UTC, c-wide commented on data/shared/citizen/scripting/v8/main.js
> +			if (listeners.length == 0) {
strict equality comparison?

2024-08-16 18:51 UTC, FabianTerhorst approved these changes
Tested and works fine 👍

2024-08-20 12:17 UTC, merged