feat(onesync): ped and player appearance data node research
citizenfx/fivem pull request #2217
Opened 2023-09-25 22:44 UTC by packfile

Adds research for `CPlayerAppearanceDataNode` and `CPedAppearanceDataNode` with most names documented. Code is behind a `#if 0` whilst the parsed data is unused

2023-11-05 14:52 UTC, Disquse approved these changes
LGTM. For future researches it's better to use new generic serializer, however since this PR is mostly for documenting, I see no problems in using old way of serializing data nodes (assuming it will be reworked in the future anyway).

2023-11-17 12:40 UTC, thorium-cfx requested changes
Thank you for this research, looks great. While reading it seems like we are deserializing here instead of serializing, but the function names say otherwise.

2023-11-17 12:40 UTC, thorium-cfx commented on code/components/citizen-server-impl/include/state/SyncTrees_Five.h
> +	void SerialiseHeadBlend(SyncParseState& state)
static?

2023-11-17 12:40 UTC, thorium-cfx commented on code/components/citizen-server-impl/include/state/SyncTrees_Five.h
> +	void SerialisePedSecondaryTask(SyncParseState& state)
static?

2023-11-23 10:37 UTC, thorium-cfx approved these changes

2024-01-19 09:36 UTC, merged