Added Examples to native docs
citizenfx/fivem pull request #2247
Opened 2023-10-17 23:58 UTC by Zaps6000

2023-11-03 18:37 UTC, 4mmonium commented on ext/native-decls/CancelEvent.md
> +            CancelEvent()
Hey, maybe I'm nitpicking, but could you please [indent](https://en.wikipedia.org/wiki/Indentation_style) this to the left using `SHIFT + Tab`?

i.e.
```lua
AddEventHandler('ptFxEvent', function(sender, eventName, eventData)
    CancelEvent()
end)
```

2023-11-03 20:01 UTC, 4mmonium requested changes
Hey there, some changes needed. An example (you can adapt) for `SendNUIMessage` can be found [here](https://docs.fivem.net/docs/scripting-reference/runtimes/lua/functions/SendNUIMessage/).

Thank you for your contribution! 🙂

2023-11-07 08:42 UTC, Zaps6000 commented
> Hey there, some changes needed. An example (you can adapt) for `SendNUIMessage` can be found [here](https://docs.fivem.net/docs/scripting-reference/runtimes/lua/functions/SendNUIMessage/).
> 
> Thank you for your contribution! 🙂

there

2023-11-07 17:20 UTC, 4mmonium commented on ext/native-decls/CancelEvent.md
> +    AddEventHandler('ptFxEvent', function(sender, eventName, eventData)
`AddEventHandler` is still incorrectly indented, remove the spaces to the left so it's properly indented. This is how it should look:

```lua
AddEventHandler('ptFxEvent', function(sender, eventName, eventData)
	CancelEvent()
end)
``` 

Code to copy:

`````
```lua
AddEventHandler('ptFxEvent', function(sender, eventName, eventData)
	CancelEvent()
end)
``` 
`````

Maybe just replace your `lua` block with what I just sent you 😀

2023-11-14 19:21 UTC, Zaps6000 commented
> Full Screen NUI guide for reference

✅

2023-11-15 02:36 UTC, Zaps6000 commented
> Looks good to me. You could possibly tell users to check out [this](https://docs.fivem.net/docs/scripting-manual/nui-development/full-screen-nui/) Full Screen NUI guide for reference as well; so the user can match up the example you created and further understand what it's doing.
> 
> But so far it looks OK for the user that is only looking for a `lua` implementation example. Thank you for your contribution! 😊

also attempted a c# and js example

2023-11-21 19:35 UTC, 4mmonium requested changes
Hey there, the effort is appreciated; requested some changes 😊

2023-11-21 19:35 UTC, 4mmonium commented on ext/native-decls/SendNuiMessage.md
> +        Function.Call((Hash)0x7AE0589093A2E088, jsonStr);
Please refrain from doing stuff like this on example code 😅

You could use something such as:

```
TriggerEvent("chat:addMessage", new
{
    color = new[] {255, 0, 0},
    multiline = true,
    args = new[] {"Me",  jsonStr}
});
```

More examples [here](https://docs.fivem.net/docs/resources/chat/events/chat-addMessage/)

2023-11-21 19:35 UTC, 4mmonium commented on ext/native-decls/SendNuiMessage.md
> +> JS Example:
Remove the `> JS Example:` line, `` ```js `` already displays this.

2023-11-21 19:35 UTC, 4mmonium commented on ext/native-decls/SendNuiMessage.md
> +> LUA Example:
Remove the `> LUA Example:` line, `` ```lua `` already displays this.

2023-11-21 19:35 UTC, 4mmonium commented on ext/native-decls/SendNuiMessage.md
> +> C# Example:
Remove the `> C# Example:` line, `` ```cs `` already displays this.

2023-11-21 19:35 UTC, 4mmonium commented on ext/native-decls/SendNuiMessage.md
> +```c#
This is supposed to be `` ```cs ``, not `` ```c# ``

2023-11-21 20:14 UTC, Zaps6000 commented
All right thanks I will update these I didnt know to much about c# so thats why but here let me get those requested changes

2024-01-08 13:08 UTC, Zaps6000 commented
😬

2024-01-23 03:28 UTC, closed without merging