feat(extra-natives/five): implement 'GET_PAUSE_MAP_POINTER_WORLD_POSITION'
citizenfx/fivem pull request #2273
Opened 2023-11-13 18:59 UTC by PichotM

This PR implements a new native that returns the world position where the pause map pointer hovers.
Tested on 1604/2189/2802/2944

2023-11-16 11:07 UTC, Disquse approved these changes
Tested on all game builds, work as expected.

2023-11-17 12:30 UTC, thorium-cfx requested changes

2023-11-17 12:30 UTC, thorium-cfx commented on code/components/extra-natives-five/src/InterfaceExtraNatives.cpp
> +	fx::ScriptEngine::RegisterNativeHandler("GET_PAUSE_MAP_POINTER_WORLD_POSITION", [=](fx::ScriptContext& context)
This'll need to be returned as a vector instead of through pointers

2023-11-17 12:30 UTC, thorium-cfx commented on ext/native-decls/GetPauseMapPointerWorldPosition.md
> +* **y**:
Please add some explanation on all of this for completeness

2023-11-17 13:18 UTC, Disquse commented
@thorium-cfx we actually have natives that return (x, y) as pointers, like `GET_NUI_CURSOR_POSITION`.

2023-11-21 20:47 UTC, thorium-cfx approved these changes

2023-12-05 15:45 UTC, merged