feat(extra-natives/five) GET_VEHICLE_GEAR_RATIO and SET_VEHICLE_GEAR_RATIO
citizenfx/fivem pull request #2409
Opened 2024-03-02 00:29 UTC by RickyB505

### Goal of this PR

These new natives will allow developers to create scripts to create custom gear ratios for vehicles.

### How is this PR achieving the goal

I added the memory editing stuff to VehicleExtraNatives.cpp to allow me to create the 2 new natives.

### This PR applies to the following area(s)

FiveM, Vehicle, Lua, JS, C#

### Successfully tested on

**Game builds:**  3095,2944,2802,2699,2612,2545,2372,2189,2060,1604

**Platforms:** Windows, Linux

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

2024-03-05 09:37 UTC, thorium-cfx commented
Hey Ricky,

Thank you for the PR, seems like you got it working, good job! Some prechecks: your commit titles don't follow our format, see https://github.com/citizenfx/fivem/actions/runs/8118915693/job/22194013573?pr=2409#step:4:83 could you resolve these?

When you are at it can you also squash the commits? Guide: https://docs.fivem.net/docs/contributing/git/squash-guide/

2024-03-05 18:51 UTC, RickyB505 commented
> Hey Ricky,
> 
> Thank you for the PR, seems like you got it working, good job! Some prechecks: your commit titles don't follow our format, see https://github.com/citizenfx/fivem/actions/runs/8118915693/job/22194013573?pr=2409#step:4:83 could you resolve these?
> 
> When you are at it can you also squash the commits? Guide: https://docs.fivem.net/docs/contributing/git/squash-guide/

should be all good now just need to let the thing run

2024-03-06 09:16 UTC, Disquse requested changes

2024-03-06 09:16 UTC, Disquse commented on code/components/extra-natives-five/src/VehicleExtraNatives.cpp
> +			context.SetResult<float>(*(float*)((char*)vehicle + VehicleGearRatioOffset + gear * sizeof(float)));
You must ensure the user won't be able to read or write out of bounds. As of b3095, it seems the biggest possible amount of gears is `<= 10`. You need to check that the passed `gear` argument isn't bigger than 10. You can also use `*(uint8_t*)(CTransmission+6)` to get this value directly from memory.
```
// The same code block we're used to calculate "VehicleGearRatioOffset".
VehicleMaxGearOffset = CurrentGearOffset + 6;
```

Here's a pattern to the function where this max gear value is being set: `BA ? ? ? ? F3 0F 11 49`

2024-03-06 09:16 UTC, Disquse commented on code/components/extra-natives-five/src/VehicleExtraNatives.cpp
> +			*(float*)((char*)vehicle + VehicleGearRatioOffset + gear * sizeof(float)) = context.GetArgument<float>(2);
Same as above.

2024-03-06 09:16 UTC, Disquse commented on ext/native-decls/GetVehicleGearRatio.md
> +---
Please add `game: gta5` here on the next line after 'apiset'.

2024-03-06 09:16 UTC, Disquse commented on ext/native-decls/GetVehicleGearRatio.md
> +Gets vehicles gear ratio on choosen gear.
Insert a newline after the end of the code block.

2024-03-06 09:16 UTC, Disquse commented on ext/native-decls/GetVehicleGearRatio.md
> +const Vehicle = GetVehiclePedIsIn(PlayerPedId(-1));
Please maintain consistent usage of the same codestyle throughout, if `lowerCamelCase` is used for variables in JS examples, keep using it across all JS examples.

2024-03-06 09:16 UTC, Disquse commented on ext/native-decls/SetVehicleGearRatio.md
> +Sets the vehicles gear ratio on choosen gear, reverse gear needs to be a negative float and forward moving gear needs to be a positive float. Refer to the examples if confused.
Insert a newline after the end of the code block.

2024-03-06 09:16 UTC, Disquse commented on ext/native-decls/SetVehicleGearRatio.md
> +## Parameters
Insert a newline after the end of the description.

2024-03-06 09:16 UTC, Disquse commented on ext/native-decls/SetVehicleGearRatio.md
> +    return
"return" isn't necessary here and in other examples too.

2024-03-06 13:20 UTC, gottfriedleibniz commented
Should we handle or document [MODIFY_VEHICLE_TOP_SPEED](https://docs.fivem.net/natives/?_0x93A3996368C94158), [SET_VEHICLE_MOD](https://docs.fivem.net/natives/?_0x6AF0636DDEDCB6DD), [REMOVE_VEHICLE_MOD](https://docs.fivem.net/natives/?_0x92D619E420858204) (VMT_GEARBOX) potentially recalculating this gear ratio array and overwriting changes made by `SET_VEHICLE_GEAR_RATIO`? Additionally b3095 introduced `0x337EF33DA3DDB990` which also repopulates the array while allowing different constants, e.g., `0.9 vs. 0.8` and `1.1 vs 1.03`

2024-03-06 21:08 UTC, RickyB505 commented
> Should we handle or document [MODIFY_VEHICLE_TOP_SPEED](https://docs.fivem.net/natives/?_0x93A3996368C94158), [SET_VEHICLE_MOD](https://docs.fivem.net/natives/?_0x6AF0636DDEDCB6DD), [REMOVE_VEHICLE_MOD](https://docs.fivem.net/natives/?_0x92D619E420858204) (VMT_GEARBOX) potentially recalculating this gear ratio array and overwriting changes made by `SET_VEHICLE_GEAR_RATIO`? Additionally b3095 introduced `0x337EF33DA3DDB990` which also repopulates the array while allowing different constants, e.g., `0.9 vs. 0.8` and `1.1 vs 1.03` in its calculations (native is tentatively named `_SET_TRANSMISSION_REDUCED_GEAR_RATIO`).

possibly might want to add to the corresponding decals that they might interfere with each other

2024-03-12 11:51 UTC, RickyB505 commented
is there anything else i need to change about this?

2024-03-12 14:50 UTC, Disquse requested changes
A few more small changes and it's good to go!

2024-03-12 14:50 UTC, Disquse commented on code/components/extra-natives-five/src/VehicleExtraNatives.cpp
> +				return;
You don't need a return here.

2024-03-12 14:50 UTC, Disquse commented on code/components/extra-natives-five/src/VehicleExtraNatives.cpp
> +			else
You don't need to set result for a `SET_` native, so this whole `else` block is useless.

2024-03-12 14:50 UTC, Disquse commented on ext/native-decls/SetVehicleGearRatio.md
> +```lua
Place a newline after `## Examples`.

2024-03-12 14:50 UTC, Disquse commented on ext/native-decls/GetVehicleGearRatio.md
> +```lua
Place a newline after `## Examples`.

2024-03-12 23:21 UTC, RickyB505 commented
@Disquse there you go all done lmk if you notice anything else that needs changing

2024-03-18 06:35 UTC, RickyB505 commented
any updates for changes needed?

2024-04-19 02:02 UTC, RickyB505 commented
i assume this is ready to merge then?

2024-05-27 13:20 UTC, Disquse commented
Tested this code in-game, works great. Thanks for your contribution; this is a nice feature to have. Apologies for the very slow review process; I was busy with a lot of other stuff. I'm attaching a debug script I made to test this feature, just in case anyone is interested in testing it out before there are any proper resources: https://pastebin.com/yDYj0sqA

2024-05-27 13:21 UTC, Disquse approved these changes

2024-05-28 11:05 UTC, merged