feat(mono-rt2): add NuiEvent attribute
citizenfx/fivem pull request #2463
Opened 2024-04-16 19:07 UTC by AvarianKnight

- allows the client to use `[NuiEvent("NuiEventName")]` to receive Nui messages

### Goal of this PR
Add similar attributes as used by `EventHandler` for Nui

### How is this PR achieving the goal
Adds new `NuiEventAttribute` and registers it via `RegisterNuiCallback`

### This PR applies to the following area(s)

ScRT: C#

### Successfully tested on
RedM

**Game builds:** N/A

**Platforms:** Windows, Linux

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### Fixes issues

2024-04-18 11:07 UTC, thorium-cfx commented
Nice addition, thank you.

Thinking if we'd instead add this to the `EventHandler` as a `Binding` option, would require some extra changes, but will enable them to be registered during runtime (not startup) as well.

2024-04-18 15:34 UTC, AvarianKnight commented
> Nice addition, thank you.
> 
> Thinking if we'd instead add this to the `EventHandler` as a `Binding` option, would require some extra changes, but will enable them to be registered during runtime (not startup) as well.

Hmm, I'll be honest I don't know if this is entirely necessary since unlike event handlers users can already do this themselves.

```c#
Natives.RegisterNuiCallback("TestHandler", new Action<ExpandoObject, Callback>((ExpandoObject obj, Callback cb) => {

}));
```

2024-04-18 16:25 UTC, thorium-cfx commented
Like discussed privately, I'm looking at this from a user's perspective, one who doesn't know about the natives system for such functionality. In that case I would also expect methods like `BaseScript.AddNuiCallback(...)` to go with this feature, which is not needed when we combine it with the event handlers. Feel free to shoot holes in that idea.

It'll look like this:
```cs
[EventHandler(Binding.NUI)]
Coroutine Function() {}
```

@manups4e can we poke your mind, maybe ask the C# community as well?

2024-04-18 16:31 UTC, manups4e commented
I'll ask in my guild for sure :) i like the idea tho

2024-04-18 18:45 UTC, AvarianKnight commented
These changes have not been tested.

After some discussion some changes where made:

The attribute was renamed from `NuiEvent` to `NuiCallback` to avoid confusion that this is an event.

The `Register/Unregister` calls were changed to public on the `BaseScript` class to make it easier for end users to find.

The `Register/Unregister` will add/remove themselves whenever a BaseScript is enabled/disabled.

There was a field added to mark a `NuiCallback` as raw, this is currently unimplemented and will be added to a future PR

2024-04-20 00:56 UTC, AvarianKnight commented
This has been tested and works but has a minor bug.

If its called in a constructor it will be enabled even if `Initialize()` and `Enabled()` isn't called. 

I opted to copy the current behavior as fixing this is outside the scope of this PR.

2024-04-23 14:49 UTC, thorium-cfx requested changes
Overall looks good, nice job, just a naming and documentation concern. To be extra sure: last changes were tested right?

2024-04-23 14:49 UTC, thorium-cfx commented on code/client/clrcore-v2/Attributes.cs
> +		public NuiCallbackAttribute(string callbackEvent, bool isRawCallback = false)
`CallbackEvent` indicates that this is the event and/or callback. I'd suggest something like `Name` or what we generally call this part:
```
                                   vvvvvvvvvvv
https://${GetParentResourceName()}/getItemInfo
```

Could you also apply the same changes in the other places?

2024-04-23 14:49 UTC, thorium-cfx commented on code/client/clrcore-v2/Native/Native.cs
> +		private static UIntPtr s_unregisterRawNuiCallback;
Could you add the hashes as comments behind them? Easier to find them :)

2024-04-24 00:35 UTC, AvarianKnight commented
> To be extra sure: last changes were tested right?

Yes the changes were tested as noted with a minor bug (noted here: https://github.com/citizenfx/fivem/issues/2476) the test code I was using is also listed there.

2024-04-24 11:08 UTC, thorium-cfx requested changes

2024-04-24 11:08 UTC, thorium-cfx commented on code/client/clrcore-v2/BaseScript.cs
> +		internal void RegisterNuiCallback(string callbackEvent, DynFunc dynFunc)
Still got some `callbackEvent` names lingering ;) also down below, can you change these to the `callbackName` as well, including all the other occurrences?

2024-04-25 10:28 UTC, thorium-cfx approved these changes
Looks good, only needs a second pair of eyes and then we can merge it 👍

2024-04-25 12:27 UTC, martonp96 approved these changes
Looks good to me, thank you for your contribution. 👍

2024-04-26 10:47 UTC, merged