Update BoneID.cs
citizenfx/fivem pull request #2663
Opened 2024-07-22 15:07 UTC by koketoo

Added the bone ids that weren't included

### Goal of this PR

Include the bond ids that weren't included
...

### How is this PR achieving the goal
Adding the bone ids
...

### This PR applies to the following area(s)

FiveM
...

### Successfully tested on

**Game builds:** .. 3095

**Platforms:** Windows

### Checklist

- [ ] Code compiles and has been tested successfully.
- [ ] Code explains itself well and/or is documented.
- [ ] My commit message explains what the changes do and what they are for.
- [ ] No extra compilation warnings are added by these changes.

### Fixes issues

2024-07-23 14:35 UTC, PsychoShock reviewed
Hello,

Small mistakes, I did some suggestions with the right bone id for you :)

Nice job.

2024-07-23 14:35 UTC, PsychoShock commented on code/client/clrcore/External/BoneID.cs
> +		SKEL_L_Finger42 = 64081,
```suggestion
		SKEL_L_Finger42 = 4154,
```

The `64081` is for the right finger42 :)

2024-07-23 14:35 UTC, PsychoShock commented on code/client/clrcore/External/BoneID.cs
> +		SKEL_L_Finger02 = 64017,
```suggestion
		SKEL_L_Finger02 = 4090,
```
The `64017` is for the right finger02 :)

2024-07-23 14:35 UTC, PsychoShock commented on code/client/clrcore/External/BoneID.cs
> +		SKEL_L_Finger12 = 64097,
```suggestion
		SKEL_L_Finger12 = 4170,
```

The `64097` is for the right finger12 :)

2024-07-23 14:35 UTC, PsychoShock commented on code/client/clrcore/External/BoneID.cs
> +		SKEL_L_Finger22 = 64113,
```suggestion
		SKEL_L_Finger22 = 4186,
```

The `64113` is for the right finger22 :)

2024-07-23 14:35 UTC, PsychoShock commented on code/client/clrcore/External/BoneID.cs
> +		SKEL_L_Finger32 = 64065,
```suggestion
		SKEL_L_Finger32 = 4138,
```

The `64065` is for the right finger32 :)

2024-07-23 14:37 UTC, koketoo commented
> Hello,
> 
> Small mistakes, I did some suggestions with the right bone id for you :)
> 
> Nice job.

Done!

2024-08-15 17:52 UTC, FabianTerhorst requested changes
Can you update your commit message to fit our commit style?

```
tweak(clrcore): add new bones
```

2024-08-16 15:25 UTC, koketoo commented
> Can you update your commit message to fit our commit style?
> 
> ```
> tweak(clrcore): add new bones
> ```

I'm starting to get desperate, the title is still wrong.

2024-08-16 15:28 UTC, koketoo commented
@FabianTerhorst Okey, let me clone the repository on GitHub Desktop.

2024-08-16 15:37 UTC, koketoo commented
@FabianTerhorst Could you please do it? I'm getting error on GitHub desktop.

2024-08-16 16:00 UTC, FabianTerhorst commented
> @FabianTerhorst Could you please do it? I'm getting error on GitHub desktop.

You can also try to apply the changes again on a new client clone. GitHub desktop is not required for that.

2024-08-18 21:04 UTC, FabianTerhorst commented
Will manually pull the changes, change the commit and remove the line format change.

2024-08-20 12:27 UTC, FabianTerhorst commented
Merged https://github.com/citizenfx/fivem/commit/14ddd6a9fe6ca0c61d5a29776be505e5e9eed20c

2024-08-20 12:27 UTC, closed without merging