Update intl.mpMenu.ts
citizenfx/fivem pull request #2745
Opened 2024-08-24 05:02 UTC by poco8537

### Goal of this PR

Clarify the South Korea server

### How is this PR achieving the goal
Currently, the South Korea server is not displayed on the home screen. If the country is ko-KO, please set it to ko-KR to resolve this issue.

### This PR applies to the following area(s)

FiveM, RedM

### Successfully tested on

**Game builds:** ALL

**Platforms:** Windows, Linux

### Checklist

- [x] Code compiles and has been tested successfully.
- [x ] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### Fixes issues

2024-08-26 09:59 UTC, nihonium-cfx requested changes
Thanks for the PR!

I'd need you to change the code to not overwrite the wrong variable though:
```ts
const [language, country] = systemLocale.split('-');

if (!country) {
  const lcLanguage = language.toLowerCase();
  const ucLanguage = language.toUpperCase();

  // Special case for Korean locale: On some systems, the Korean locale might be returned as `ko-KO`,
  // but it should be standardized to `ko-KR` for consistency with South Korean regional settings.
  if (lcLanguage === 'ko') {
    return 'ko-KR';
  }

  // Windows has some locales such as `pl` which should expand to `pl-PL`
  return `${lcLanguage}-${ucLanguage}`;
}
```

2024-08-28 08:06 UTC, nihonium-cfx commented
Please only keep one commit, otherwise LGTM.

2024-08-28 14:39 UTC, poco8537 commented
I'll reopen the PR.

2024-08-28 14:39 UTC, closed without merging

2024-08-28 14:47 UTC, Gogsi commented
You don't have to close and open a new PR. You can run these git commands in your repository folder to combine the 3 commits into one.
```
git reset --soft HEAD~3 
git commit -m "new commit message"
git push --force
```

2024-08-28 15:01 UTC, poco8537 commented
I didn't know how to do that. I just re-created the PR. #2755