feat(onesync): custom distance culling radius for entities
citizenfx/fivem pull request #526
Opened 2020-09-03 03:47 UTC by PichotM

2020-09-03 03:50 UTC, PichotM commented
it does basically the same thing as https://media.giphy.com/media/loLPei2rdrMqotZ4Jd/giphy.gif
but instead of setting a custom radius for a player, we set it for a specific entity
It is relatively useful for a player that needs to control an entity outside its scope

2020-09-03 05:47 UTC, zirconiium commented
big vouch for this PR. It's an absolute must-have rn for 1sync/infinity, i personnally need it for my black-hole event but whatever, i hope this will be pushed. nice pr.

2020-09-06 02:47 UTC, ShadowOfVoid commented
+1 really liked the idea and i think its really needed !

2020-09-06 08:28 UTC, blattersturm requested changes
Memory model stuff.

2020-09-06 08:28 UTC, blattersturm commented on code/components/citizen-server-impl/include/state/ServerGameState.h
> +		return overrideCullingRadius != NULL ? (overrideCullingRadius * overrideCullingRadius) : (424.0f * 424.0f);
`!= 0.0f`, maybe pre-multiply on set?

2020-09-06 08:28 UTC, blattersturm commented on code/components/citizen-server-impl/include/state/ServerGameState.h
> +	float overrideCullingRadius;
`= 0.0f;`. Without any default set either here or in the constructor it'll be uninitialized memory, which could be _anything_!

2020-09-06 08:28 UTC, blattersturm commented on code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
> +				entity->overrideCullingRadius = NULL;
again, NULL is for a pointer (and won't exist on Linux), `0.0f` is more likely and by then will actually not need an extra `if` (unless you're trying to keep the 'negative float' part).

2020-09-06 12:57 UTC, PichotM commented
Fixed

2020-09-06 13:09 UTC, blattersturm approved these changes

2020-09-06 13:10 UTC, merged