feat(voip/mumble): Add MumbleSetAudioInputIntent
citizenfx/fivem pull request #709
Opened 2021-04-29 15:05 UTC by nikez

2021-04-29 15:07 UTC, Disquse commented on code/components/voip-mumble/src/MumbleAudioInput.cpp
> +	OnKillNetworkDone.Connect([=]() {
rip bracket :(

2021-04-30 09:09 UTC, blattersturm requested changes
Few changes.

2021-04-30 09:09 UTC, blattersturm commented on ext/native-decls/MumbleSetAudioInputIntent.md
> +void MUMBLE_SET_AUDIO_INPUT_INTENT(int intentIndex);
Hash, since it's a hash.

2021-04-30 09:09 UTC, blattersturm commented on code/components/voip-mumble/component.json
> +		"gta:core:five"
Plain `gta:core` or maybe just ICoreGameInit usage instead of OnKillNetworkDone?

2021-05-02 05:50 UTC, blattersturm approved these changes
Sure. Shame on you for adding 2 extra commits and not just squashing it.

2021-05-02 05:54 UTC, merged