fix(scripting/v8): Default omitted timeout to 0
citizenfx/fivem pull request #769
Opened 2021-07-19 23:27 UTC by cactysman

... otherwise the [check](https://github.com/citizenfx/fivem/blob/6de33031bddd96fd0cec08a4b0bf34e22836d303/data/shared/citizen/scripting/v8/timer.js#L120) fails because nothing is greater than `undefined`.

This breaks interop with incorrect usage (as found in some npm modules) of `setTimeout` and `setInterval` where omitted timeouts are meant to default to 0 ([spec § 8.6.10](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers)), but instead just don't run the function at all due to the missing default/min value of 0.

I also renamed the property for convenience.

2021-07-21 07:48 UTC, nihonium-cfx requested changes

2021-07-21 07:48 UTC, nihonium-cfx commented on data/shared/citizen/scripting/v8/timer.js
> +    function setTimer(timer, callback, timeout) {
Given how `setTimeout` is in fact just `setInterval` but will die after first run this should be kept as `interval`.

2021-07-29 08:27 UTC, blattersturm commented
Can you actually squash the commits in your branch?

2021-07-30 00:21 UTC, cactysman commented
> Can you actually squash the commits in your branch?

Done

2021-07-30 18:29 UTC, blattersturm commented
btw do you even test the code you pr? nice syntax error 🙃

2021-07-30 19:01 UTC, cactysman commented
> btw do you even test the code you pr? nice syntax error 🙃

Of course I did and honestly I don't see what's supposed to be wrong here.

2021-07-30 19:02 UTC, blattersturm commented
You're missing `interval:`.

2021-07-30 19:08 UTC, cactysman commented
God damn it. That's what you get from rebasing on your phone.
It's fixed now.

2021-07-30 21:58 UTC, closed without merging